#!/usr/bin/env -S uv run --quiet python
import http.server, os, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
http.server.test(
    HandlerClass=http.server.SimpleHTTPRequestHandler,
    port=int(sys.argv[1]) if len(sys.argv) > 1 else 8000,
    bind=os.environ.get("HOST", "127.0.0.1"),
)
