#!/bin/bash
# Compile the macOS *outer* kernel: the KVM-capable arm64 Linux image that
# Apple's `container machine` boots, inside which sparkbox runs firecracker.
# Apple's stock machine kernel has no KVM, so nested virt is impossible without
# this file. Output: macos/out/vmlinux-kvm (a flat arch/arm64/boot/Image).
#
# ============================ THIS IS THE ESCAPE HATCH ======================
#
# Compiling a Linux kernel is not an onboarding step. The DEFAULT path is
# macos/kernel/fetch.sh: download `vmlinux-macos-arm64` from the release being
# provisioned and verify it against SHA256_OUTER_KERNEL in that release's
# manifest-darwin-arm64.env. This script is what CI runs to produce that asset,
# and what a developer runs to change the kernel config or bump the version.
# poc.sh only calls it when SPARKBOX_KERNEL_SOURCE=build.
#
# ======================= REPRODUCIBILITY: READ THIS =========================
#
# The compiler is not merely used, it is embedded: the resolved config carries
#   CONFIG_CC_VERSION_TEXT="gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0"
# and the kernel banner compiled into the image reads
#   Linux version 6.14.9-sparkbox-poc (sparkbox@apple-container)
#   (gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, GNU ld (...) 2.42) #1 SMP ...
#
# CI therefore supplies SPARKBOX_KERNEL_BUILD_IMAGE as the immutable digest of
# Dockerfile.builder. That image contains the resolved compiler packages and
# the two SHA-verified source inputs. The digest is part of the kernel's content
# cache key, so changing the toolchain or inputs creates a new artifact instead
# of silently changing an old one. A cache miss builds independently at -j3 and
# -j4 and compares the results before the bundle is admitted to the cache.
#
# A developer invoking this script directly gets the convenient fallback:
# the pinned Ubuntu rootfs runs apt-get against today's archive. That local path
# is deterministic within the resolved toolchain but not pinned across time.
# Pass the CI builder digest in SPARKBOX_KERNEL_BUILD_IMAGE to reproduce CI.
#
# The claims made and gated here are:
#
#   1. DETERMINISM WITHIN A TOOLCHAIN. Everything else that varies between two
#      builds is pinned: source tarball + base config by SHA-256, builder image
#      by digest, KBUILD_BUILD_USER/HOST/TIMESTAMP fixed, LOCALVERSION_AUTO off
#      (and no .git for setlocalversion to find anyway), a fixed /build path so
#      no host path leaks in, a fresh container so the build number stays #1,
#      LC_ALL/TZ fixed, no modules (so no autogenerated module-signing key), no
#      BTF/pahole, no RANDSTRUCT seed, no BUILD_SALT, and `Image` rather than a
#      compressed variant that would carry its own timestamp. The one variable
#      left is -j. SPARKBOX_KERNEL_REPRO_CHECK=1 checks it sequentially for a
#      local build; CI performs the same check on two parallel ARM runners.
#   2. INTEGRITY OF WHAT WE SHIPPED. The release records the SHA-256 of the file
#      it published; every Mac verifies its download against it. That is what
#      protects a user. CI additionally records its content key and exact builder
#      digest in the released kernel manifest.
#
# KNOWN_GOOD_KERNEL_SHA256 is a review tripwire. A mismatch is reported with the
# builder and compiler version, but it is not a failure unless
# SPARKBOX_KERNEL_STRICT_SHA=1: deliberately updating the builder is allowed to
# change the kernel and its content cache key.
#
# Env overrides:
#   SPARKBOX_CONTAINER_CMD          container runtime (default: `container` on
#                                   macOS, `docker` on linux)
#   SPARKBOX_KERNEL_BUILD_IMAGE     exact builder image (CI passes repo@digest)
#   SPARKBOX_KERNEL_INPUTS_IN_IMAGE source/config live in /kernel-inputs
#   SPARKBOX_BUILD_CPUS             `container` only (default 8)
#   SPARKBOX_KERNEL_BUILD_MEMORY    `container` only (default 16G)
#   SPARKBOX_KERNEL_BUILD_JOBS      make -j (default: nproc - 1)
#   SPARKBOX_KERNEL_REPRO_CHECK=1   build twice at different -j, compare
#   SPARKBOX_KERNEL_STRICT_SHA=1    a known-good mismatch is a hard failure
set -euo pipefail

LINUX_VERSION="6.14.9"
LINUX_URL="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${LINUX_VERSION}.tar.xz"
LINUX_SHA256="390cdde032719925a08427270197ef55db4e90c09d454e9c3554157292c9f361"

APPLE_CONFIG_TAG="0.5.0"
APPLE_CONFIG_URL="https://raw.githubusercontent.com/apple/containerization/${APPLE_CONFIG_TAG}/kernel/config-arm64"
APPLE_CONFIG_SHA256="0b05408d7d5f5d5e941d89767780dc87a2e90e2f8ef20ec6f8cf11a3037f9f36"

KERNEL_BUILD_IMAGE="${SPARKBOX_KERNEL_BUILD_IMAGE:-docker.io/library/ubuntu:24.04@sha256:4fbb8e6a8395de5a7550b33509421a2bafbc0aab6c06ba2cef9ebffbc7092d90}"

# The bytes one build produced, on an M4 Max on 2026-07-25 with
# gcc 13.3.0-6ubuntu2~24.04.1 / binutils 2.42. See the header: a witness, not a
# law. Empty it to silence the comparison entirely.
KNOWN_GOOD_KERNEL_SHA256="7bb865dfc2dfb6578d41a9fb2d044299c626377ff69c540b15108afb75dd080c"

if [[ "${1:-}" == "--print-builder-args" ]]; then
  printf 'LINUX_VERSION=%s\n' "${LINUX_VERSION}"
  printf 'LINUX_URL=%s\n' "${LINUX_URL}"
  printf 'LINUX_SHA256=%s\n' "${LINUX_SHA256}"
  printf 'APPLE_CONFIG_TAG=%s\n' "${APPLE_CONFIG_TAG}"
  printf 'APPLE_CONFIG_URL=%s\n' "${APPLE_CONFIG_URL}"
  printf 'APPLE_CONFIG_SHA256=%s\n' "${APPLE_CONFIG_SHA256}"
  exit 0
fi

# What `uname -r` must report inside the machine. gateway-verify.sh asserts the
# same string from the other side, so changing either without the other turns a
# working machine into a failing preflight.
KERNEL_RELEASE="${LINUX_VERSION}-sparkbox-poc"
BANNER_PREFIX="Linux version ${KERNEL_RELEASE} (sparkbox@apple-container)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MACOS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${SPARKBOX_KERNEL_OUT_DIR:-${MACOS_DIR}/out}"
DOWNLOAD_DIR="${OUT_DIR}/downloads"
SOURCE_ARCHIVE="${DOWNLOAD_DIR}/linux-${LINUX_VERSION}.tar.xz"
APPLE_CONFIG="${DOWNLOAD_DIR}/apple-config-arm64-${APPLE_CONFIG_TAG}"
FRAGMENT="${SCRIPT_DIR}/sparkbox-arm64.fragment"
KERNEL_OUTPUT="${OUT_DIR}/vmlinux-kvm"
CONFIG_OUTPUT="${OUT_DIR}/kernel.config"
MANIFEST_OUTPUT="${OUT_DIR}/kernel-manifest.txt"

BUILD_CPUS="${SPARKBOX_BUILD_CPUS:-8}"
BUILD_MEMORY="${SPARKBOX_KERNEL_BUILD_MEMORY:-16G}"

die() {
  echo "error: $*" >&2
  exit 1
}

# sha256sum on linux, shasum on macOS. The container half never calls this, so
# the builder image needs neither.
sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

verify_sha256() {
  local path="$1"
  local expected="$2"
  local actual
  actual="$(sha256_file "${path}")"
  [[ "${actual}" == "${expected}" ]] \
    || die "checksum mismatch for ${path}: got ${actual}, want ${expected}"
}

download_verified() {
  local url="$1"
  local path="$2"
  local expected="$3"
  local tmp="${path}.tmp.$$"

  if [[ -f "${path}" ]]; then
    verify_sha256 "${path}" "${expected}"
    echo "using verified $(basename "${path}")"
    return
  fi

  trap 'rm -f -- "${tmp}"' RETURN
  echo "downloading ${url}"
  curl --fail --location --silent --show-error \
    --proto '=https' --tlsv1.2 --retry 3 \
    --output "${tmp}" "${url}"
  verify_sha256 "${tmp}" "${expected}"
  mv "${tmp}" "${path}"
  trap - RETURN
}

# ------------------------------------------------------------ inner half --
# Runs inside the pinned builder container. Reachable from CI directly (docker
# run -e SPARKBOX_KERNEL_BUILD_CONTAINER=1), which is why every determinism knob
# lives here rather than in the caller.
build_inside_container() {
  export DEBIAN_FRONTEND=noninteractive
  if [[ "${SPARKBOX_KERNEL_TOOLCHAIN_READY:-0}" != "1" ]]; then
    # Local escape-hatch builds retain the old convenient default. CI uses the
    # digest-pinned Dockerfile.builder image, where these packages are already
    # installed and their resolved versions are part of the image digest.
    apt-get update
    apt-get install -y --no-install-recommends \
      bc \
      bison \
      build-essential \
      ca-certificates \
      flex \
      libelf-dev \
      libssl-dev \
      python3 \
      xz-utils
    rm -rf /var/lib/apt/lists/*
  fi

  local source_archive="${SOURCE_ARCHIVE}"
  local apple_config="${APPLE_CONFIG}"
  if [[ "${SPARKBOX_KERNEL_INPUTS_IN_IMAGE:-0}" == "1" ]]; then
    source_archive="/kernel-inputs/linux-${LINUX_VERSION}.tar.xz"
    apple_config="/kernel-inputs/apple-config-arm64-${APPLE_CONFIG_TAG}"
  fi
  verify_sha256 "${source_archive}" "${LINUX_SHA256}"
  verify_sha256 "${apple_config}" "${APPLE_CONFIG_SHA256}"

  # A FRESH tree every time, at a FIXED path, and both matter for the hash:
  # scripts/build-version increments a `.version` file, so a reused tree yields
  # "#2 SMP" in the banner; and building anywhere but /build would bake the
  # caller's absolute paths into the image. Caching this directory between CI
  # runs is the tempting optimisation that would silently break both.
  rm -rf /build
  mkdir -p /build
  tar -xf "${source_archive}" \
    -C /build --strip-components=1
  cp "${apple_config}" /build/.config

  cd /build
  scripts/kconfig/merge_config.sh -m .config /src/sparkbox-arm64.fragment
  make olddefconfig

  local jobs
  jobs="${SPARKBOX_KERNEL_BUILD_JOBS:-}"
  if [[ -z "${jobs}" ]]; then
    jobs="$(nproc)"
    if [[ "${jobs}" -gt 1 ]]; then
      jobs=$((jobs - 1))
    fi
  fi

  export KBUILD_BUILD_USER=sparkbox
  export KBUILD_BUILD_HOST=apple-container
  # The trailing "UTC" is load-bearing, not decoration: usr/Makefile feeds this
  # string to gen_initramfs.sh, which parses it with `date -d`. Drop the zone
  # and a builder in another timezone shifts every initramfs mtime — and the
  # hash with them. TZ=UTC below belts the same braces.
  export KBUILD_BUILD_TIMESTAMP="2025-05-29 09:26:00 UTC"
  export TZ=UTC LC_ALL=C LANG=C
  echo "building with -j${jobs}"
  make -j"${jobs}" Image

  cp arch/arm64/boot/Image /out/vmlinux-kvm
  cp .config /out/kernel.config

  # Apple's `container` remaps ownership over virtiofs, but a plain `docker run`
  # writes /out as root and the CI step that uploads these files is not root.
  # Hand them back rather than making the caller sudo.
  if [[ -n "${SPARKBOX_OUT_UID:-}" ]]; then
    chown "${SPARKBOX_OUT_UID}:${SPARKBOX_OUT_GID:-${SPARKBOX_OUT_UID}}" \
      /out/vmlinux-kvm /out/kernel.config
  fi
}

if [[ "${SPARKBOX_KERNEL_BUILD_CONTAINER:-0}" == "1" ]]; then
  build_inside_container
  exit 0
fi

# ------------------------------------------------------------ outer half --

# The builder must be NATIVE arm64, and not only for speed. Cross-compiling with
# gcc-13-aarch64-linux-gnu is a different package build than native gcc-13, so
# CONFIG_CC_VERSION_TEXT differs and the known-good hash becomes unreachable by
# construction. It would also fail confusingly: this script passes no ARCH= at
# all (kbuild derives SUBARCH from uname -m), so a cross build would configure
# for x86 and die at `cp arch/arm64/boot/Image`.
case "$(uname -s)" in
  Darwin)
    [[ "$(uname -m)" == "arm64" ]] || die "the kernel builder requires Apple Silicon"
    CONTAINER_CMD="${SPARKBOX_CONTAINER_CMD:-container}"
    ;;
  Linux)
    [[ "$(uname -m)" == "aarch64" ]] \
      || die "the kernel builder must run on a native aarch64 host (this is $(uname -m)); cross-compiling produces a different, valid kernel with a different checksum"
    CONTAINER_CMD="${SPARKBOX_CONTAINER_CMD:-docker}"
    ;;
  *)
    die "unsupported build host $(uname -s); macOS or linux/aarch64"
    ;;
esac
command -v "${CONTAINER_CMD}" >/dev/null \
  || die "${CONTAINER_CMD} is not installed (set SPARKBOX_CONTAINER_CMD)"
command -v curl >/dev/null || die "curl is required"
[[ -f "${FRAGMENT}" ]] || die "missing ${FRAGMENT}"

# run_builder re-execs this script inside the pinned image. Apple's CLI and
# docker spell the same three concepts differently enough to need the branch;
# both mount the kernel dir read-only and macos/out read-write, and both get a
# throwaway container (see the /build note above).
run_builder() {
  local jobs="$1"
  # Expanded below as ${input_env_args[@]+"${input_env_args[@]}"}, not the
  # obvious "${input_env_args[@]}". This array is empty whenever the caller did
  # not set SPARKBOX_KERNEL_INPUTS_IN_IMAGE, and expanding an empty array under
  # `set -u` is an unbound-variable error in bash before 4.4 — so the plain form
  # aborts this script on macOS, whose /bin/bash is 3.2.57, with
  # `input_env_args[@]: unbound variable` and no kernel. It went unnoticed
  # because the default path is fetch.sh (download the CI-built asset) and CI
  # runs this on linux under bash 5. Same defect the gateway entrypoint has on
  # macOS; hack/dev/gateway.sh works around it by re-execing under a newer bash.
  local input_env_args=()
  # Preserve the image's default when the caller did not select an input mode,
  # but carry an explicit choice across the outer/inner script boundary.
  if [[ "${SPARKBOX_KERNEL_INPUTS_IN_IMAGE+x}" == "x" ]]; then
    input_env_args=(
      --env "SPARKBOX_KERNEL_INPUTS_IN_IMAGE=${SPARKBOX_KERNEL_INPUTS_IN_IMAGE}"
    )
  fi
  case "$(basename "${CONTAINER_CMD}")" in
    container)
      "${CONTAINER_CMD}" run --rm --arch arm64 \
        --cpus "${BUILD_CPUS}" \
        --memory "${BUILD_MEMORY}" \
        --volume "${SCRIPT_DIR}:/src:ro" \
        --volume "${OUT_DIR}:/out" \
        --env SPARKBOX_KERNEL_BUILD_CONTAINER=1 \
        --env "SPARKBOX_KERNEL_BUILD_JOBS=${jobs}" \
        ${input_env_args[@]+"${input_env_args[@]}"} \
        "${KERNEL_BUILD_IMAGE}" \
        /bin/bash /src/build.sh
      ;;
    *)
      "${CONTAINER_CMD}" run --rm --platform linux/arm64 \
        --volume "${SCRIPT_DIR}:/src:ro" \
        --volume "${OUT_DIR}:/out" \
        --env SPARKBOX_KERNEL_BUILD_CONTAINER=1 \
        --env "SPARKBOX_KERNEL_BUILD_JOBS=${jobs}" \
        ${input_env_args[@]+"${input_env_args[@]}"} \
        --env "SPARKBOX_OUT_UID=$(id -u)" \
        --env "SPARKBOX_OUT_GID=$(id -g)" \
        "${KERNEL_BUILD_IMAGE}" \
        /bin/bash /src/build.sh
      ;;
  esac
}

# kernel_banner pulls the compiled-in version string out of the Image. `strings`
# would be shorter but is binutils, which a minimal runner may not have; tr+grep
# is in every base system. Two banners are embedded — the template with an empty
# build number and the resolved one — so match the numbered variant.
kernel_banner() {
  LC_ALL=C tr -c '[:print:]\n' '\n' < "$1" \
    | grep -m1 -E '^Linux version [^ ]+ \(.*\) #[0-9]+ SMP ' || true
}

# verify_outputs gates the artifact on what it must CONTAIN, not on what we
# hoped merge_config would do. olddefconfig silently drops a symbol whose
# dependencies went unmet, and the failure would only surface as a machine that
# boots but has no KVM.
verify_outputs() {
  local required_symbols=(
    CONFIG_KVM
    CONFIG_VIRTUALIZATION
    CONFIG_TUN
    CONFIG_BLK_DEV_LOOP
    CONFIG_XFS_FS
    CONFIG_EXT4_FS
    CONFIG_NETFILTER
    CONFIG_IP_NF_IPTABLES
    CONFIG_IP_NF_NAT
    CONFIG_NETFILTER_XT_TARGET_REDIRECT
    # sparkbox-net.sh parks the sluice resolver and edge addresses on `type
    # dummy` interfaces. Apple's base config leaves it unset and this kernel has
    # no loadable modules, so its absence is fatal to the VM node and shows up
    # only as iproute2's `Error: Unknown device type.` — which names no symbol.
    CONFIG_DUMMY
    CONFIG_BPF_JIT
  )
  local symbol
  for symbol in "${required_symbols[@]}"; do
    grep -qx "${symbol}=y" "${CONFIG_OUTPUT}" \
      || die "${CONFIG_OUTPUT} does not contain ${symbol}=y"
  done
  grep -qx "CONFIG_LOCALVERSION=\"-sparkbox-poc\"" "${CONFIG_OUTPUT}" \
    || die "${CONFIG_OUTPUT} has the wrong local version"

  # The banner is the only place the determinism knobs can be observed in the
  # OUTPUT rather than in the inputs we hoped they reached. It catches
  # KBUILD_BUILD_USER/HOST/TIMESTAMP silently not applying, and it catches a
  # reused build tree, which shows up as "#2 SMP" and nothing else.
  local banner
  banner="$(kernel_banner "${KERNEL_OUTPUT}")"
  [[ -n "${banner}" ]] \
    || die "no 'Linux version ... #N SMP' banner in ${KERNEL_OUTPUT}; it may not be a kernel Image"
  [[ "${banner}" == "${BANNER_PREFIX}"* ]] \
    || die "kernel banner is '${banner}', expected it to start with '${BANNER_PREFIX}'. KBUILD_BUILD_USER/HOST or CONFIG_LOCALVERSION did not take effect"
  [[ "${banner}" == *"#1 SMP"* ]] \
    || die "kernel banner is '${banner}': the build number is not #1, so the build tree was reused. Every reuse changes the output bytes; build in a fresh container"
  KERNEL_BANNER="${banner}"
}

mkdir -p "${DOWNLOAD_DIR}"
if [[ "${SPARKBOX_KERNEL_INPUTS_IN_IMAGE:-0}" == "1" ]]; then
  echo "using kernel sources embedded in ${KERNEL_BUILD_IMAGE}"
else
  download_verified "${LINUX_URL}" "${SOURCE_ARCHIVE}" "${LINUX_SHA256}"
  download_verified "${APPLE_CONFIG_URL}" "${APPLE_CONFIG}" "${APPLE_CONFIG_SHA256}"
fi

echo "building Linux ${LINUX_VERSION} in a disposable ARM64 container (${CONTAINER_CMD})"
run_builder "${SPARKBOX_KERNEL_BUILD_JOBS:-}"

KERNEL_BANNER=""
verify_outputs

fragment_sha256="$(sha256_file "${FRAGMENT}")"
config_sha256="$(sha256_file "${CONFIG_OUTPUT}")"
kernel_sha256="$(sha256_file "${KERNEL_OUTPUT}")"
# The compiler string, lifted from the resolved config. This is the cheap
# tripwire: it moves BEFORE anyone has to wonder why the kernel hash moved.
cc_version="$(sed -n 's/^CONFIG_CC_VERSION_TEXT="\(.*\)"$/\1/p' "${CONFIG_OUTPUT}" | head -1)"

# ---------------------------------------------------- determinism check --
#
# Build a second time at a DIFFERENT -j and compare. Same runner, same apt
# state, so this deliberately does not test toolchain drift (nothing can, in a
# single run) — it tests that the build is a pure function of its inputs, and it
# exercises the one variable this script does not pin. Kernel builds are
# believed -j-invariant; this is where that belief gets checked instead of
# assumed.
if [[ "${SPARKBOX_KERNEL_REPRO_CHECK:-0}" == "1" ]]; then
  first_jobs="${SPARKBOX_KERNEL_BUILD_JOBS:-default}"
  second_jobs=2
  if [[ "${SPARKBOX_KERNEL_BUILD_JOBS:-}" == "2" ]]; then
    second_jobs=3
  fi
  echo
  echo "== determinism check: rebuilding at -j${second_jobs} (first pass: -j${first_jobs}) =="
  mv "${KERNEL_OUTPUT}" "${OUT_DIR}/vmlinux-kvm.pass1"
  cp "${CONFIG_OUTPUT}" "${OUT_DIR}/kernel.config.pass1"
  run_builder "${second_jobs}"
  second_sha256="$(sha256_file "${KERNEL_OUTPUT}")"
  if [[ "${second_sha256}" != "${kernel_sha256}" ]]; then
    if ! diff -q "${OUT_DIR}/kernel.config.pass1" "${CONFIG_OUTPUT}" >/dev/null; then
      echo "the two passes resolved DIFFERENT configs (see ${OUT_DIR}/kernel.config.pass1)" >&2
    fi
    die "the kernel build is not deterministic: -j${first_jobs} produced ${kernel_sha256}, -j${second_jobs} produced ${second_sha256}. Both images are kept (${OUT_DIR}/vmlinux-kvm.pass1 and ${KERNEL_OUTPUT}). Nothing downstream can pin this artifact until that is explained"
  fi
  rm -f "${OUT_DIR}/vmlinux-kvm.pass1" "${OUT_DIR}/kernel.config.pass1"
  echo "identical across two builds at different -j: ${kernel_sha256}"
  REPRO_CHECKED="j${first_jobs}+j${second_jobs}"
else
  REPRO_CHECKED="no"
fi

# --------------------------------------------------- known-good witness --
KNOWN_GOOD_STATUS="unset"
STRICT_FAIL=0
if [[ -n "${KNOWN_GOOD_KERNEL_SHA256}" ]]; then
  if [[ "${kernel_sha256}" == "${KNOWN_GOOD_KERNEL_SHA256}" ]]; then
    KNOWN_GOOD_STATUS="match"
    echo "sha256 matches the recorded known-good build"
  else
    KNOWN_GOOD_STATUS="drift"
    {
      echo
      echo "WARNING: this kernel differs from the recorded known-good build."
      echo "  got:  ${kernel_sha256}"
      echo "  want: ${KNOWN_GOOD_KERNEL_SHA256}"
      echo "  compiler: ${cc_version:-unknown}"
      echo
      echo "That is expected when the pinned builder was deliberately updated:"
      echo "gcc and binutils version strings are compiled into the kernel banner,"
      echo "so even a packaging-only bump changes these bytes. Confirm the builder"
      echo "digest and compiler above explain the difference, exercise the kernel,"
      echo "then update KNOWN_GOOD_KERNEL_SHA256."
    } >&2
    # Deferred rather than immediate: a strict run that dies here would leave no
    # kernel-manifest.txt, and the manifest is exactly what the person now
    # investigating the drift needs (both hashes, the compiler, the banner).
    [[ "${SPARKBOX_KERNEL_STRICT_SHA:-0}" != "1" ]] || STRICT_FAIL=1
  fi
fi

{
  printf 'kernel_source=built\n'
  printf 'linux_version=%s\n' "${LINUX_VERSION}"
  printf 'linux_url=%s\n' "${LINUX_URL}"
  printf 'linux_sha256=%s\n' "${LINUX_SHA256}"
  printf 'apple_config_tag=%s\n' "${APPLE_CONFIG_TAG}"
  printf 'apple_config_url=%s\n' "${APPLE_CONFIG_URL}"
  printf 'apple_config_sha256=%s\n' "${APPLE_CONFIG_SHA256}"
  printf 'kernel_build_image=%s\n' "${KERNEL_BUILD_IMAGE}"
  printf 'fragment_sha256=%s\n' "${fragment_sha256}"
  printf 'config_sha256=%s\n' "${config_sha256}"
  printf 'kernel_sha256=%s\n' "${kernel_sha256}"
  printf 'kernel_release=%s\n' "${KERNEL_RELEASE}"
  # The three fields that explain a hash, recorded next to it so a future drift
  # is a two-line diff instead of an investigation.
  printf 'cc_version=%s\n' "${cc_version}"
  printf 'kernel_banner=%s\n' "${KERNEL_BANNER}"
  printf 'known_good_sha256=%s\n' "${KNOWN_GOOD_KERNEL_SHA256}"
  printf 'known_good_status=%s\n' "${KNOWN_GOOD_STATUS}"
  printf 'repro_checked=%s\n' "${REPRO_CHECKED}"
} > "${MANIFEST_OUTPUT}"

echo "kernel:   ${KERNEL_OUTPUT}"
echo "config:   ${CONFIG_OUTPUT}"
echo "manifest: ${MANIFEST_OUTPUT}"
echo "sha256:   ${kernel_sha256}"

[[ "${STRICT_FAIL}" -eq 0 ]] \
  || die "SPARKBOX_KERNEL_STRICT_SHA=1 and the kernel drifted from the known-good build; ${MANIFEST_OUTPUT} records what changed"
