// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: node/v1/node.proto

package nodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeControl_GetInventory_FullMethodName           = "/sparkbox.node.v1.NodeControl/GetInventory"
	NodeControl_WatchEvents_FullMethodName            = "/sparkbox.node.v1.NodeControl/WatchEvents"
	NodeControl_GetCapacity_FullMethodName            = "/sparkbox.node.v1.NodeControl/GetCapacity"
	NodeControl_Health_FullMethodName                 = "/sparkbox.node.v1.NodeControl/Health"
	NodeControl_GetVitals_FullMethodName              = "/sparkbox.node.v1.NodeControl/GetVitals"
	NodeControl_EnsureRunning_FullMethodName          = "/sparkbox.node.v1.NodeControl/EnsureRunning"
	NodeControl_BeginCreate_FullMethodName            = "/sparkbox.node.v1.NodeControl/BeginCreate"
	NodeControl_BeginPause_FullMethodName             = "/sparkbox.node.v1.NodeControl/BeginPause"
	NodeControl_BeginArchive_FullMethodName           = "/sparkbox.node.v1.NodeControl/BeginArchive"
	NodeControl_BeginResize_FullMethodName            = "/sparkbox.node.v1.NodeControl/BeginResize"
	NodeControl_BeginReboot_FullMethodName            = "/sparkbox.node.v1.NodeControl/BeginReboot"
	NodeControl_BeginRename_FullMethodName            = "/sparkbox.node.v1.NodeControl/BeginRename"
	NodeControl_BeginDestroy_FullMethodName           = "/sparkbox.node.v1.NodeControl/BeginDestroy"
	NodeControl_BeginSetPinned_FullMethodName         = "/sparkbox.node.v1.NodeControl/BeginSetPinned"
	NodeControl_BeginResyncEnvironment_FullMethodName = "/sparkbox.node.v1.NodeControl/BeginResyncEnvironment"
	NodeControl_BeginSnapshot_FullMethodName          = "/sparkbox.node.v1.NodeControl/BeginSnapshot"
	NodeControl_BeginDeleteSnapshot_FullMethodName    = "/sparkbox.node.v1.NodeControl/BeginDeleteSnapshot"
	NodeControl_BeginFork_FullMethodName              = "/sparkbox.node.v1.NodeControl/BeginFork"
	NodeControl_MarkActive_FullMethodName             = "/sparkbox.node.v1.NodeControl/MarkActive"
	NodeControl_RecordKey_FullMethodName              = "/sparkbox.node.v1.NodeControl/RecordKey"
	NodeControl_ApplyNetworkPolicy_FullMethodName     = "/sparkbox.node.v1.NodeControl/ApplyNetworkPolicy"
	NodeControl_GetNetworkUsage_FullMethodName        = "/sparkbox.node.v1.NodeControl/GetNetworkUsage"
	NodeControl_GetOperation_FullMethodName           = "/sparkbox.node.v1.NodeControl/GetOperation"
	NodeControl_WatchOperation_FullMethodName         = "/sparkbox.node.v1.NodeControl/WatchOperation"
)

// NodeControlClient is the client API for NodeControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeControl is the typed, durable control plane between a Sparkbox gateway
// and one approved node. Guest byte streams deliberately do not belong here.
type NodeControlClient interface {
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*Inventory, error)
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InventoryEvent], error)
	GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*Capacity, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetVitals(ctx context.Context, in *GetVitalsRequest, opts ...grpc.CallOption) (*Vitals, error)
	EnsureRunning(ctx context.Context, in *EnsureRunningRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginCreate(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginPause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginArchive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginResize(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginReboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginDestroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginSetPinned(ctx context.Context, in *SetPinnedRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginResyncEnvironment(ctx context.Context, in *ResyncEnvironmentRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginDeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*Operation, error)
	BeginFork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*Operation, error)
	// MarkActive and RecordKey are intentionally cheap bookkeeping operations.
	// They are idempotent and may be coalesced by either peer.
	MarkActive(ctx context.Context, in *MarkActiveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RecordKey(ctx context.Context, in *RecordKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ApplyNetworkPolicy(ctx context.Context, in *ApplyNetworkPolicyRequest, opts ...grpc.CallOption) (*Operation, error)
	GetNetworkUsage(ctx context.Context, in *GetNetworkUsageRequest, opts ...grpc.CallOption) (*GetNetworkUsageResponse, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	WatchOperation(ctx context.Context, in *WatchOperationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Operation], error)
}

type nodeControlClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeControlClient(cc grpc.ClientConnInterface) NodeControlClient {
	return &nodeControlClient{cc}
}

func (c *nodeControlClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*Inventory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Inventory)
	err := c.cc.Invoke(ctx, NodeControl_GetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InventoryEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeControl_ServiceDesc.Streams[0], NodeControl_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, InventoryEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_WatchEventsClient = grpc.ServerStreamingClient[InventoryEvent]

func (c *nodeControlClient) GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*Capacity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Capacity)
	err := c.cc.Invoke(ctx, NodeControl_GetCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NodeControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) GetVitals(ctx context.Context, in *GetVitalsRequest, opts ...grpc.CallOption) (*Vitals, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vitals)
	err := c.cc.Invoke(ctx, NodeControl_GetVitals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) EnsureRunning(ctx context.Context, in *EnsureRunningRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_EnsureRunning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginCreate(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginPause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginArchive(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginResize(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginResize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginReboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginReboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginRename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginDestroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginDestroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginSetPinned(ctx context.Context, in *SetPinnedRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginSetPinned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginResyncEnvironment(ctx context.Context, in *ResyncEnvironmentRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginResyncEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginDeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginDeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) BeginFork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_BeginFork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) MarkActive(ctx context.Context, in *MarkActiveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeControl_MarkActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) RecordKey(ctx context.Context, in *RecordKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeControl_RecordKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) ApplyNetworkPolicy(ctx context.Context, in *ApplyNetworkPolicyRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_ApplyNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) GetNetworkUsage(ctx context.Context, in *GetNetworkUsageRequest, opts ...grpc.CallOption) (*GetNetworkUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkUsageResponse)
	err := c.cc.Invoke(ctx, NodeControl_GetNetworkUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, NodeControl_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeControlClient) WatchOperation(ctx context.Context, in *WatchOperationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Operation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeControl_ServiceDesc.Streams[1], NodeControl_WatchOperation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchOperationRequest, Operation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_WatchOperationClient = grpc.ServerStreamingClient[Operation]

// NodeControlServer is the server API for NodeControl service.
// All implementations must embed UnimplementedNodeControlServer
// for forward compatibility.
//
// NodeControl is the typed, durable control plane between a Sparkbox gateway
// and one approved node. Guest byte streams deliberately do not belong here.
type NodeControlServer interface {
	GetInventory(context.Context, *GetInventoryRequest) (*Inventory, error)
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[InventoryEvent]) error
	GetCapacity(context.Context, *GetCapacityRequest) (*Capacity, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	GetVitals(context.Context, *GetVitalsRequest) (*Vitals, error)
	EnsureRunning(context.Context, *EnsureRunningRequest) (*Operation, error)
	BeginCreate(context.Context, *CreateRequest) (*Operation, error)
	BeginPause(context.Context, *PauseRequest) (*Operation, error)
	BeginArchive(context.Context, *ArchiveRequest) (*Operation, error)
	BeginResize(context.Context, *ResizeRequest) (*Operation, error)
	BeginReboot(context.Context, *RebootRequest) (*Operation, error)
	BeginRename(context.Context, *RenameRequest) (*Operation, error)
	BeginDestroy(context.Context, *DestroyRequest) (*Operation, error)
	BeginSetPinned(context.Context, *SetPinnedRequest) (*Operation, error)
	BeginResyncEnvironment(context.Context, *ResyncEnvironmentRequest) (*Operation, error)
	BeginSnapshot(context.Context, *SnapshotRequest) (*Operation, error)
	BeginDeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*Operation, error)
	BeginFork(context.Context, *ForkRequest) (*Operation, error)
	// MarkActive and RecordKey are intentionally cheap bookkeeping operations.
	// They are idempotent and may be coalesced by either peer.
	MarkActive(context.Context, *MarkActiveRequest) (*emptypb.Empty, error)
	RecordKey(context.Context, *RecordKeyRequest) (*emptypb.Empty, error)
	ApplyNetworkPolicy(context.Context, *ApplyNetworkPolicyRequest) (*Operation, error)
	GetNetworkUsage(context.Context, *GetNetworkUsageRequest) (*GetNetworkUsageResponse, error)
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	WatchOperation(*WatchOperationRequest, grpc.ServerStreamingServer[Operation]) error
	mustEmbedUnimplementedNodeControlServer()
}

// UnimplementedNodeControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeControlServer struct{}

func (UnimplementedNodeControlServer) GetInventory(context.Context, *GetInventoryRequest) (*Inventory, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInventory not implemented")
}
func (UnimplementedNodeControlServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[InventoryEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedNodeControlServer) GetCapacity(context.Context, *GetCapacityRequest) (*Capacity, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapacity not implemented")
}
func (UnimplementedNodeControlServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedNodeControlServer) GetVitals(context.Context, *GetVitalsRequest) (*Vitals, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVitals not implemented")
}
func (UnimplementedNodeControlServer) EnsureRunning(context.Context, *EnsureRunningRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureRunning not implemented")
}
func (UnimplementedNodeControlServer) BeginCreate(context.Context, *CreateRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginCreate not implemented")
}
func (UnimplementedNodeControlServer) BeginPause(context.Context, *PauseRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginPause not implemented")
}
func (UnimplementedNodeControlServer) BeginArchive(context.Context, *ArchiveRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginArchive not implemented")
}
func (UnimplementedNodeControlServer) BeginResize(context.Context, *ResizeRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginResize not implemented")
}
func (UnimplementedNodeControlServer) BeginReboot(context.Context, *RebootRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginReboot not implemented")
}
func (UnimplementedNodeControlServer) BeginRename(context.Context, *RenameRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginRename not implemented")
}
func (UnimplementedNodeControlServer) BeginDestroy(context.Context, *DestroyRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginDestroy not implemented")
}
func (UnimplementedNodeControlServer) BeginSetPinned(context.Context, *SetPinnedRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginSetPinned not implemented")
}
func (UnimplementedNodeControlServer) BeginResyncEnvironment(context.Context, *ResyncEnvironmentRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginResyncEnvironment not implemented")
}
func (UnimplementedNodeControlServer) BeginSnapshot(context.Context, *SnapshotRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginSnapshot not implemented")
}
func (UnimplementedNodeControlServer) BeginDeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginDeleteSnapshot not implemented")
}
func (UnimplementedNodeControlServer) BeginFork(context.Context, *ForkRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginFork not implemented")
}
func (UnimplementedNodeControlServer) MarkActive(context.Context, *MarkActiveRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkActive not implemented")
}
func (UnimplementedNodeControlServer) RecordKey(context.Context, *RecordKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordKey not implemented")
}
func (UnimplementedNodeControlServer) ApplyNetworkPolicy(context.Context, *ApplyNetworkPolicyRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyNetworkPolicy not implemented")
}
func (UnimplementedNodeControlServer) GetNetworkUsage(context.Context, *GetNetworkUsageRequest) (*GetNetworkUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkUsage not implemented")
}
func (UnimplementedNodeControlServer) GetOperation(context.Context, *GetOperationRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedNodeControlServer) WatchOperation(*WatchOperationRequest, grpc.ServerStreamingServer[Operation]) error {
	return status.Error(codes.Unimplemented, "method WatchOperation not implemented")
}
func (UnimplementedNodeControlServer) mustEmbedUnimplementedNodeControlServer() {}
func (UnimplementedNodeControlServer) testEmbeddedByValue()                     {}

// UnsafeNodeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeControlServer will
// result in compilation errors.
type UnsafeNodeControlServer interface {
	mustEmbedUnimplementedNodeControlServer()
}

func RegisterNodeControlServer(s grpc.ServiceRegistrar, srv NodeControlServer) {
	// If the following call panics, it indicates UnimplementedNodeControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeControl_ServiceDesc, srv)
}

func _NodeControl_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_GetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeControlServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, InventoryEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_WatchEventsServer = grpc.ServerStreamingServer[InventoryEvent]

func _NodeControl_GetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).GetCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_GetCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).GetCapacity(ctx, req.(*GetCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_GetVitals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVitalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).GetVitals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_GetVitals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).GetVitals(ctx, req.(*GetVitalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_EnsureRunning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureRunningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).EnsureRunning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_EnsureRunning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).EnsureRunning(ctx, req.(*EnsureRunningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginCreate(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginPause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginArchive(ctx, req.(*ArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginResize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginResize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginResize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginResize(ctx, req.(*ResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginReboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginReboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginReboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginReboot(ctx, req.(*RebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginRename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginDestroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginDestroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginSetPinned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPinnedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginSetPinned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginSetPinned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginSetPinned(ctx, req.(*SetPinnedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginResyncEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResyncEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginResyncEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginResyncEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginResyncEnvironment(ctx, req.(*ResyncEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginDeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginDeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginDeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginDeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_BeginFork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).BeginFork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_BeginFork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).BeginFork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_MarkActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).MarkActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_MarkActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).MarkActive(ctx, req.(*MarkActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_RecordKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).RecordKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_RecordKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).RecordKey(ctx, req.(*RecordKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_ApplyNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).ApplyNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_ApplyNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).ApplyNetworkPolicy(ctx, req.(*ApplyNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_GetNetworkUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).GetNetworkUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_GetNetworkUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).GetNetworkUsage(ctx, req.(*GetNetworkUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeControlServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeControl_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeControlServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeControl_WatchOperation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchOperationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeControlServer).WatchOperation(m, &grpc.GenericServerStream[WatchOperationRequest, Operation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeControl_WatchOperationServer = grpc.ServerStreamingServer[Operation]

// NodeControl_ServiceDesc is the grpc.ServiceDesc for NodeControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sparkbox.node.v1.NodeControl",
	HandlerType: (*NodeControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventory",
			Handler:    _NodeControl_GetInventory_Handler,
		},
		{
			MethodName: "GetCapacity",
			Handler:    _NodeControl_GetCapacity_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _NodeControl_Health_Handler,
		},
		{
			MethodName: "GetVitals",
			Handler:    _NodeControl_GetVitals_Handler,
		},
		{
			MethodName: "EnsureRunning",
			Handler:    _NodeControl_EnsureRunning_Handler,
		},
		{
			MethodName: "BeginCreate",
			Handler:    _NodeControl_BeginCreate_Handler,
		},
		{
			MethodName: "BeginPause",
			Handler:    _NodeControl_BeginPause_Handler,
		},
		{
			MethodName: "BeginArchive",
			Handler:    _NodeControl_BeginArchive_Handler,
		},
		{
			MethodName: "BeginResize",
			Handler:    _NodeControl_BeginResize_Handler,
		},
		{
			MethodName: "BeginReboot",
			Handler:    _NodeControl_BeginReboot_Handler,
		},
		{
			MethodName: "BeginRename",
			Handler:    _NodeControl_BeginRename_Handler,
		},
		{
			MethodName: "BeginDestroy",
			Handler:    _NodeControl_BeginDestroy_Handler,
		},
		{
			MethodName: "BeginSetPinned",
			Handler:    _NodeControl_BeginSetPinned_Handler,
		},
		{
			MethodName: "BeginResyncEnvironment",
			Handler:    _NodeControl_BeginResyncEnvironment_Handler,
		},
		{
			MethodName: "BeginSnapshot",
			Handler:    _NodeControl_BeginSnapshot_Handler,
		},
		{
			MethodName: "BeginDeleteSnapshot",
			Handler:    _NodeControl_BeginDeleteSnapshot_Handler,
		},
		{
			MethodName: "BeginFork",
			Handler:    _NodeControl_BeginFork_Handler,
		},
		{
			MethodName: "MarkActive",
			Handler:    _NodeControl_MarkActive_Handler,
		},
		{
			MethodName: "RecordKey",
			Handler:    _NodeControl_RecordKey_Handler,
		},
		{
			MethodName: "ApplyNetworkPolicy",
			Handler:    _NodeControl_ApplyNetworkPolicy_Handler,
		},
		{
			MethodName: "GetNetworkUsage",
			Handler:    _NodeControl_GetNetworkUsage_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _NodeControl_GetOperation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _NodeControl_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchOperation",
			Handler:       _NodeControl_WatchOperation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node/v1/node.proto",
}

const (
	GatewayIdentity_IssueToken_FullMethodName       = "/sparkbox.node.v1.GatewayIdentity/IssueToken"
	GatewayIdentity_DescribeIdentity_FullMethodName = "/sparkbox.node.v1.GatewayIdentity/DescribeIdentity"
)

// GatewayIdentityClient is the client API for GatewayIdentity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayIdentity is hosted by the gateway for a node's guest metadata
// service. The authenticated node identity, never a request field, determines
// which placements the caller may speak for.
type GatewayIdentityClient interface {
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	DescribeIdentity(ctx context.Context, in *DescribeIdentityRequest, opts ...grpc.CallOption) (*IdentityDescription, error)
}

type gatewayIdentityClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayIdentityClient(cc grpc.ClientConnInterface) GatewayIdentityClient {
	return &gatewayIdentityClient{cc}
}

func (c *gatewayIdentityClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, GatewayIdentity_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayIdentityClient) DescribeIdentity(ctx context.Context, in *DescribeIdentityRequest, opts ...grpc.CallOption) (*IdentityDescription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityDescription)
	err := c.cc.Invoke(ctx, GatewayIdentity_DescribeIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayIdentityServer is the server API for GatewayIdentity service.
// All implementations must embed UnimplementedGatewayIdentityServer
// for forward compatibility.
//
// GatewayIdentity is hosted by the gateway for a node's guest metadata
// service. The authenticated node identity, never a request field, determines
// which placements the caller may speak for.
type GatewayIdentityServer interface {
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	DescribeIdentity(context.Context, *DescribeIdentityRequest) (*IdentityDescription, error)
	mustEmbedUnimplementedGatewayIdentityServer()
}

// UnimplementedGatewayIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayIdentityServer struct{}

func (UnimplementedGatewayIdentityServer) IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedGatewayIdentityServer) DescribeIdentity(context.Context, *DescribeIdentityRequest) (*IdentityDescription, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeIdentity not implemented")
}
func (UnimplementedGatewayIdentityServer) mustEmbedUnimplementedGatewayIdentityServer() {}
func (UnimplementedGatewayIdentityServer) testEmbeddedByValue()                         {}

// UnsafeGatewayIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayIdentityServer will
// result in compilation errors.
type UnsafeGatewayIdentityServer interface {
	mustEmbedUnimplementedGatewayIdentityServer()
}

func RegisterGatewayIdentityServer(s grpc.ServiceRegistrar, srv GatewayIdentityServer) {
	// If the following call panics, it indicates UnimplementedGatewayIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayIdentity_ServiceDesc, srv)
}

func _GatewayIdentity_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayIdentityServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayIdentity_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayIdentityServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayIdentity_DescribeIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayIdentityServer).DescribeIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayIdentity_DescribeIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayIdentityServer).DescribeIdentity(ctx, req.(*DescribeIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayIdentity_ServiceDesc is the grpc.ServiceDesc for GatewayIdentity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayIdentity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sparkbox.node.v1.GatewayIdentity",
	HandlerType: (*GatewayIdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueToken",
			Handler:    _GatewayIdentity_IssueToken_Handler,
		},
		{
			MethodName: "DescribeIdentity",
			Handler:    _GatewayIdentity_DescribeIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node/v1/node.proto",
}
