#!/usr/bin/env bash
# Capture the identity generated by an existing Sparkbox Pod into the
# sparkbox-identity Secret without writing key material to the terminal.
set -euo pipefail
umask 077

usage() {
  cat <<'EOF'
usage: capture-identity.sh [options]

Options:
  --context CONTEXT       kubectl context (default: current context)
  --namespace NAMESPACE   Sparkbox namespace (default: sparkbox-poc)
  --pod NAME              source Pod (default: sole running Sparkbox Pod)
  --source-dir PATH       source key directory (default: auto-detect)
  --secret NAME           destination Secret (default: sparkbox-identity)
EOF
}

context=
namespace=sparkbox-poc
pod=
source_dir=
secret=sparkbox-identity

while [ "$#" -gt 0 ]; do
  case "$1" in
    --context)
      context=${2:?--context requires a value}
      shift 2
      ;;
    --namespace)
      namespace=${2:?--namespace requires a value}
      shift 2
      ;;
    --pod)
      pod=${2:?--pod requires a value}
      pod=${pod#pod/}
      shift 2
      ;;
    --source-dir)
      source_dir=${2:?--source-dir requires a value}
      shift 2
      ;;
    --secret)
      secret=${2:?--secret requires a value}
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

for resource_name in "$namespace" "$secret"; do
  case "$resource_name" in
    ''|-*|*[!a-z0-9.-]*)
      echo "namespace and secret names must use lowercase DNS-name characters" >&2
      exit 2
      ;;
  esac
done
case "$pod" in
  -*|*[!a-zA-Z0-9.-]*)
    echo "--pod contains unsupported characters" >&2
    exit 2
    ;;
esac

if [ -z "$context" ]; then
  context=$(kubectl config current-context)
fi
k=(kubectl --context "$context" -n "$namespace")

if [ -z "$pod" ]; then
  running_pods=$(
    "${k[@]}" get pods \
      -l app.kubernetes.io/name=sparkbox \
      --field-selector status.phase=Running \
      -o name
  )
  pods=()
  while IFS= read -r candidate; do
    [ -n "$candidate" ] && pods+=("${candidate#pod/}")
  done <<< "$running_pods"
  if [ "${#pods[@]}" -ne 1 ]; then
    echo "found ${#pods[@]} running Sparkbox Pods in $namespace; pass --pod explicitly" >&2
    exit 1
  fi
  pod=${pods[0]}
else
  "${k[@]}" get pod "$pod" >/dev/null
fi

# These are sufficient to reconstruct every long-lived identity after local
# control state is lost. Renewable leaf certificates and derived public keys do
# not belong in the Secret.
required_files=(
  gateway_host_key.pem
  gateway_upstream_key.pem
  oidc_signing_key.pem
  node_ca_cert.pem
  node_ca_key.pem
  gateway_control_key.pem
)
optional_files=(
  oidc_signing_key_prev.pem
)

if [ -n "$source_dir" ]; then
  source_candidates=("$source_dir")
else
  # Prefer the active mounted Secret after migration. /state is the original
  # CKS POC layout; /control is the split layout used during the cutover.
  source_candidates=(
    /run/sparkbox/keys
    /var/lib/sparkbox/control
    /var/lib/sparkbox/state
  )
fi

source_dir=
for candidate in "${source_candidates[@]}"; do
  if "${k[@]}" exec "$pod" -- sh -c '
    directory=$1
    shift
    for file do
      [ -s "$directory/$file" ] || exit 1
    done
  ' sh "$candidate" "${required_files[@]}" 2>/dev/null; then
    source_dir=$candidate
    break
  fi
done
[ -n "$source_dir" ] || {
  echo "no source directory in Pod $pod contains the complete Sparkbox identity" >&2
  echo "checked: ${source_candidates[*]}" >&2
  exit 1
}

temporary_dir=$(mktemp -d)
chmod 0700 "$temporary_dir"
captured_files=()
cleanup() {
  local file
  for file in "${required_files[@]}" "${optional_files[@]}"; do
    rm -f "$temporary_dir/$file"
  done
  rmdir "$temporary_dir" 2>/dev/null || true
}
trap cleanup EXIT

capture_file() {
  local file=$1
  "${k[@]}" exec "$pod" -- sh -c 'cat "$1/$2"' sh "$source_dir" "$file" \
    > "$temporary_dir/$file"
  chmod 0600 "$temporary_dir/$file"
  [ -s "$temporary_dir/$file" ] || {
    echo "captured identity file is empty: $file" >&2
    exit 1
  }
  captured_files+=("$file")
}

for file in "${required_files[@]}"; do
  capture_file "$file"
done
if ! grep -q '^-----BEGIN CERTIFICATE-----$' "$temporary_dir/node_ca_cert.pem"; then
  echo "captured node_ca_cert.pem is not a PEM certificate" >&2
  exit 1
fi
for file in \
  gateway_host_key.pem gateway_upstream_key.pem oidc_signing_key.pem \
  node_ca_key.pem gateway_control_key.pem; do
  if ! grep -q 'PRIVATE KEY-----$' "$temporary_dir/$file"; then
    echo "captured identity file is not a PEM private key: $file" >&2
    exit 1
  fi
done

for file in "${optional_files[@]}"; do
  if "${k[@]}" exec "$pod" -- test -s "$source_dir/$file" 2>/dev/null; then
    capture_file "$file"
    if ! grep -q 'PRIVATE KEY-----$' "$temporary_dir/$file"; then
      echo "captured identity file is not a PEM private key: $file" >&2
      exit 1
    fi
  fi
done

secret_args=(create secret generic "$secret")
for file in "${captured_files[@]}"; do
  secret_args+=(--from-file="$file=$temporary_dir/$file")
done
"${k[@]}" "${secret_args[@]}" --dry-run=client -o yaml \
  | "${k[@]}" apply -f - >/dev/null

echo "Captured Sparkbox identity from Pod $pod:$source_dir into Secret $namespace/$secret."
printf 'Files: %s\n' "${captured_files[*]}"
