apiVersion: v1
kind: ServiceAccount
metadata:
  name: sparkbox-gateway
  namespace: sparkbox-poc
  labels:
    app.kubernetes.io/name: sparkbox
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: sparky
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sparkbox-node
  namespace: sparkbox-poc
  labels:
    app.kubernetes.io/name: sparkbox
    app.kubernetes.io/component: vm-node
    app.kubernetes.io/part-of: sparky
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sparkbox-device-plugin
  namespace: sparkbox-poc
  labels:
    app.kubernetes.io/name: sparkbox
    app.kubernetes.io/component: device-plugin
    app.kubernetes.io/part-of: sparky
automountServiceAccountToken: false
